### ISSUE TITLE
Feature Request: Add timeout for specific requests

### ISSUE THREAD

**Issue by medavian** [testerum/testerum#11]
Hey Team,

As part of our testing for specific API requests, we have SLAs that we enforce for these requests. 

Is it possible to add a time assertion to ensure that the request is completed with a specific time (in milliseconds)?

Let me know if you would like some further information on this request.

Thanks again for a great tool.

Kind Regards,
Darrin

**Comment by cvmocanu** [comment]
Hi @medavian,

Thanks for your feedback.

We didn't have anything like this, but we just implemented it :wink::
![assert-http-response-duration](https://user-images.githubusercontent.com/59873/96385897-31501d80-1197-11eb-951d-20a1e843afd7.png)

The ``httpResponse`` will get a ``durationInMillis`` property that can be used for asserts.

Expect a release in a few days (so we can also include the fix for #10).

Also if you want, and you have time, we can have a call with you to know each other better and to understand your needs. We can also show you some new features that are not documented yet.

If you want to get in touch with us please send an email to: contact@testerum.com with the details on how we can get in touch with you (email, Skype, Teams, etc).

**Comment by medavian** [comment]
Hey @cvmocanu,

Thanks for the quick response. 

Looking forward to the new release.

I'll reach out to you on email, would be good to have a catchup with a discussion. 

Kind Regards,
Darrin

**Comment by medavian** [comment]
Hey @cvmocanu , @ionut-pruteanu ,

Thanks for the great product and assistance.

This is working great also. Is allowing us to put some basic SLAs around ensuring our requests are timely.

Awesome product and team ..
