### ISSUE TITLE
Feature Request: Add annotations to Steps

### ISSUE THREAD

**Issue by medavian** [testerum/testerum#16]
Hey Team,

We have been building out our test cases in Testerum and have occasionally wanted to add notes to a step as to why it has been added or why it is configured a certain way.

Is it possible to add a field to each step as a note or annotation? Even a single line field that we can put a URL or link to a wiki page or the like.

Keep up the great work, Testerum is making my life so much easier having everything in the one place. Not spread across multiple applications.

Kind Regards,
Darrin

**Comment by imariusgradinaru** [comment]
Hello Medavian,

I'm Marius from Testerum team.
In Testerum you can add a description or notes to your steps (composed steps).
In order to add notes or a description, you have to edit the step.

![foto1-edit-custom-step](https://user-images.githubusercontent.com/44640232/98486077-883b9680-221b-11eb-9ff0-1cc236c83beb.png)

-----------------------------------------------------------------------------------------------------------------------------------

![foto2-edit-custom-step](https://user-images.githubusercontent.com/44640232/98486088-925d9500-221b-11eb-85e8-7e80f4a07352.png)

Once you added the description, save the step and now you can see it when you hover over the Info Icon.

![foto3-edit-custom-step](https://user-images.githubusercontent.com/44640232/98486101-a6a19200-221b-11eb-99dd-57f5169272de.png)

Also, if you go to Steps and select your Custom Step, you will see the description there as well. 
From here you can also modify or add a description to your custom steps.

![foto4-edit-custom-step](https://user-images.githubusercontent.com/44640232/98486104-aacdaf80-221b-11eb-8833-ffac4e82197c.png)

I hope this answer was helpful.

Thank you for writing to us! Please contact us if you have other questions. 
We are always happy to help you! 

Regards,
Marius Gradinaru

**Comment by ionut-pruteanu** [comment]
I will close this issue, I hope the response from Marius is fixing your request
