### ISSUE TITLE
Feature Request: implement toString for ValidHttpResponse

### ISSUE THREAD

**Issue by aldaris** [testerum/testerum#22]
When trying to log all variables using a script with content `testLogger.warn(testVariables.toMap());`
the output can contain things like this:
```
httpResponse=com.testerum.model.resources.http.response.ValidHttpResponse@79f90a3a
```
It would help debugging tests if the whole response could be printed to the logs instead.

**Comment by ionut-pruteanu** [comment]
Hi Aldaris,

To log all the variables you can use the step:
debug / When I log all the variables

Is interesting that you don't see the HttpResponse in a nice way. I see that we have implemented the .toString method.
I will try to reproduce it and see if I can do something about it.

Because you are helping us so much to identify issues we can also have a call. To discuss more about possible improvements, how you use Testerum, what can we do better. If you want you can write to me at contact@testerum.com and we can exchange email addresses and setup a call (Skype, Zoom, Teams, etc)

**Comment by aldaris** [comment]
Ah, looks like I've been running 3.1.21, while the latest version is 3.7.7 (I've downloaded the zip from the Testerum website not too long ago, not sure how I missed so many versions). The toString method was first introduced in 3.2.0 it looks like (368c911f6bfc7efc0300925de079aea212741d3e).
