### ISSUE TITLE
Some general questions about using Testerum

### ISSUE THREAD

**Issue by Ajhad1** [testerum/testerum#6]
Background: Looking to use Testerum but after some initial testing I have a few questions.

Questions:

- Is there a way to set Variables when running all tests in a feature? 
- - Using the Sample Project learn by examples. There are several tests, login, receive owners list, and create a new owner. How would I use the set the variable for the username and password when running all of the tests of the feature?

- I saw in the documentation reference to "before" and "after" hooks, how do I set those?

- I have created some tests in the Sample Project based on the examples, how can I move them to a new project?

- Is it possible to export the project and use it on another installation of Testerum? (My environments are completely separated but would share many tests. Would it be possible to "share" a test? I would rather not have to rewrite the exact same tests again.)

- I saw in the documentation, "tests are versioned with your code" what does this mean and how do I leverage it?

- I saw in the documentation, "fully extensible platform. You can create any custom integration you want in a very easy manner." is there any documentation for this?

- Same question about "can create custom integrations"

**Comment by cvmocanu** [comment]
Hi @Ajhad1,

> Is there a way to set Variables when running all tests in a feature?

Testerum is similar to Postman, in that we use environments to group variables. See here for more information: https://testerum.com/documentation/ui/variables-parameters-and-scenarios/
If you are running the tests from the command-line (e.g. from your CI/CD server (Jenkins, Bamboo, etc.)), you can use the ``--var-env`` argument to set a particular environment, or ``--var`` to set individual variables. See more information here: https://testerum.com/documentation/backend/runner/

> I saw in the documentation reference to "before" and "after" hooks, how do I set those?

Not sure where in the documentation you saw this.
Currently hooks are planned, but not yet implemented.
As a (hacky) workaround, you can group the steps you want as part of a hook in a composed step, and manually add this composed step before/after each test.

There is some manual work involved, because you need to add this to every test, but at least you will be able to modify the "hook" in a single place (by modifying the composed step) and the change will be visible in all tests.

> I have created some tests in the Sample Project based on the examples, how can I move them to a new project?

Testerum stores everything in files, on the hard-drive.
Simply create a new project and copy the files under the ``features`` directory from the demo project to your project (use your favorite file manager).
To copy the environments (variables), copy the file ``.testerum/variables.json``.
The demo tests can be found at ``<directory-where-you-installed-testerum>/demo/tests/``.

> Is it possible to export the project and use it on another installation of Testerum? (My environments are completely separated but would share many tests. Would it be possible to "share" a test? I would rather not have to rewrite the exact same tests again.)

The recommended way to share the tests between Testerum installations is to use a code versioning system, like git.
Actually we worked hard to make this easy, by storing the tests in plain-text files.
Each tester/developer would checkout the tests locally, make changes, and then commit and push, allowing the other colleagues to see the changes. Your CI/CD server (e.g. Jenkins or Bamboo) would also checkout the tests from e.g. git and then use the command-line runner to run the tests.

You would use environment variables to define things that are different, like URLs, hostnames, etc.
If you want to execute a different set of tests in different environments, you could do this by organizing your tests, like this:
* common
* env-1
* env-2

Then, in environment 1, you would execute both ``common`` and ``env-1``, and in environment 2, you would execute both ``common`` and ``env-2``.
To select what is executed:
* from the UI, use different run configurations (see the drop-down on the top toolbar, to the left of the variables). This allows you to select exactly what sub-set of tests/features you want to execute
* from the command-line runner, you would use multiple ``--test-path`` arguments. More information here: https://testerum.com/documentation/backend/runner/

> I saw in the documentation, "tests are versioned with your code" what does this mean and how do I leverage it?

A Testerum project is saved to a set of files on the hard-drive. We don't use any other database or binary files.
To use this, just add these files to a versioning system like git.

> I saw in the documentation, "fully extensible platform. You can create any custom integration you want in a very easy manner." is there any documentation for this?

By "integration" we mean custom basic steps. We use these basic steps to integrate with different technologies, like HTTP, Selenium, databases, etc.
There is no documentation about this yet, but we plan to add it soon.
What this means, is that you can create custom steps in java (or any other JVM language) very easy, by just writing a method and adding some annotations. It's very similar to how you do it in cucumber. If you need help with this before we get to write the documentation, I guess we could provide you with a sample project that shows how this works.

> Same question about "can create custom integrations"

This means: "can create custom basic steps". See the previous answer.

BTW, check the tutorial videos also to get a better grasp on how Testerum works: https://testerum.com/videos/

Hope this is of help.

**Comment by Ajhad1** [comment]
@cvmocanu 
Thank you so much for the detailed response, you answered my questions perfectly. 
I would love to get my hands on the sample project with the custom basic steps.

A few follow up questions:
If I add the "after" composed step to each test, how to do I get it to run if the test fails?
Do you have a timeline for the hooks and other new features?
Do you handle feature requests here or is there someplace else I can post them?

-----------------
I am looking at the documentation for the reports. Here are some questions about them.

Is there a way to output the results to something other than HTML and the console?
The ideal would be a way to output the results into a third-party library that could generate the reports. (i.e. [cucumber-reporting](https://github.com/damianszczepanik/cucumber-reporting))

What is the difference between the managed reports and the PRETTY reports?

**Comment by ionut-pruteanu** [comment]
Hi Ajhad,
I am Ionut, one of the Testerum developer. 

I appreciate your feedback and if you have time I would like to have a call with you to know each other better and to understand your needs. I can also show you some new features that are not documented yet.

If you want to get in touch with me please send an email to: contact@testerum.com with the details on how I can get in touch with you (email, Skype, Teams, etc).
